version: '3.8'
services:
  db:
    image: mysql:8
    container_name: schedulle-mysql
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./my-data:/var/lib/mysql
    ports:
      - "3306:3306"